spring:
  # 开发环境数据库配置 - 使用SQLite
  datasource:
    url: jdbc:sqlite:${user.home}/.dreamer-ai-chat/dev-database.db
    driver-class-name: org.sqlite.JDBC
    username: 
    password: 
  
  # JPA配置 - SQLite专用
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
        format_sql: true
        # SQLite特定配置
        jdbc:
          batch_size: 5
        order_inserts: true
        order_updates: true
  
  # Flyway配置 - 开发环境
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration-sqlite
    # SQLite不支持某些高级特性，可能需要忽略某些迁移
    ignore-migration-patterns: "*:missing"
  
  # AI模型配置 - 开发环境
  ai:
    # 千问配置 - 开发环境
    qianwen:
      api-key: 1111
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      
    # 星火配置 - 开发环境
    xinghuo:
      api-key: ${XINGHUO_API_KEY:fake-xinghuo-key-for-dev}
      base-url: https://spark-api.xf-yun.com
      
    # 豆包配置 - 开发环境
    doubao:
      api-key: ${DOUBAO_API_KEY:fake-doubao-key-for-dev}
      base-url: https://ark.cn-beijing.volces.com/api/v3
      
    # DeepSeek配置 - 开发环境
    deepseek:
      api-key: ${DEEPSEEK_API_KEY:fake-deepseek-key-for-dev}
      base-url: https://api.deepseek.com

# 开发环境特定配置
app:
  chat:
    timeout-seconds: 60  # 开发环境增加超时时间便于调试

# 日志配置 - 开发环境更详细
logging:
  level:
    com.dreamer.chat: DEBUG
    org.springframework.ai: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG 